In [1]:
import numpy as np
rng=np.random.default_rng(seed=42)

hours_studied=rng.integers(1,10,size=50)
attendance=rng.integers(50,100,size=50)
prev_score=rng.integers(40,95,size=50)
predicted_score=(hours_studied*5)+(attendance*0.3)+(prev_score*0.5)
dataset=np.column_stack([hours_studied,attendance,prev_score,predicted_score])
print(dataset)

[[  1.   87.   85.   73.6]
 [  7.   59.   50.   77.7]
 [  6.   68.   84.   92.4]
 [  4.   73.   40.   61.9]
 [  4.   74.   83.   83.7]
 [  8.   52.   83.   97.1]
 [  1.   77.   82.   69.1]
 [  7.   57.   76.   90.1]
 [  2.   87.   65.   68.6]
 [  1.   84.   78.   69.2]
 [  5.   96.   55.   81.3]
 [  9.   87.   82.  112.1]
 [  7.   68.   70.   90.4]
 [  7.   98.   65.   96.9]
 [  7.   70.   67.   89.5]
 [  8.   66.   71.   95.3]
 [  5.   95.   42.   74.5]
 [  2.   68.   47.   53.9]
 [  8.   53.   53.   82.4]
 [  5.   73.   46.   69.9]
 [  5.   89.   64.   83.7]
 [  4.   59.   76.   75.7]
 [  2.   73.   75.   69.4]
 [  9.   56.   65.   94.3]
 [  8.   84.   87.  108.7]
 [  6.   73.   71.   87.4]
 [  4.   66.   44.   61.8]
 [  8.   61.   82.   99.3]
 [  5.   78.   71.   83.9]
 [  4.   83.   74.   81.9]
 [  5.   97.   71.   89.6]
 [  3.   71.   70.   71.3]
 [  1.   58.   44.   44.4]
 [  5.   91.   70.   87.3]
 [  8.   81.   83.  105.8]
 [  1.   85.   56.   58.5]
 [  8.   54.   73.   92.7]
 