In [1]:
import numpy as np
print(np.__version__)

2.4.4


In [3]:
import numpy as np
array = np.array([1,2,3,4])

print(array*3)

[ 3  6  9 12]


In [19]:
import numpy as np

array=np.array([[["a",2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,"s"],[7,8,9]],
               [[1,2,3],[4,"s",6],[7,8,9]]])
#print(array.shape)
#print(array)
#print(array[1][1][2])
print(array[0,0,0]+array[1,1,2]+array[2,1,1])

ass


In [16]:
#slicing
import numpy as np
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

#array[start:end:step] step means agar aap ku even rows hona hai to aap step to 2 rakhsakte to array sirf even rows ku slect karta odd rows ku steps me chhodeta
#print(array[1:4:2])

#for column array[row,column]
print(array[2:,0:2])

[[ 9 10]
 [13 14]]


In [24]:
#Arithmrtic
import numpy as np
#array=np.array([1.344 ,2.3423 ,3.383])
# print(np.sqrt(array))
# print(np.round(array))
# print(np.floor(array))
# print(np.ceil(array))

radius=np.array([1.2231,6.32156,9.1364])
print(np.pi*(radius**2))



[  4.6997397  125.54470523 262.24069243]


In [26]:
#broadcasting
#broadcasting can be only done iff the corresponding rows and columns are equal or if one of them 1
import numpy as np
array1=np.array([[1,2,3,4,5,6,7,8,9,10]])
array2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(array1.shape)
print(array2.shape)
print(array1*array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [12]:
#Random
import numpy as np
array=np.array([1,2,3,4,5])
ran=np.random.default_rng(seed=61)
ran.shuffle(array)
print(array)
print(ran.integers(1,7))

#Choice object
# fruits=np.array(["apple","banana","Mango","pineapple"])
# ran=np.random.default_rng()
# fruit=ran.choice(fruits)
# print(fruit)

[5 4 1 3 2]
5


In [37]:
import numpy as np
rng=np.random.default_rng(seed=42)

hours_studied=rng.integers(1,10,size=50)
attendance=rng.integers(50,100,size=50)
prev_score=rng.integers(40,95,size=50)
predicted_score=(hours_studied*5)+(attendance*0.3)+(prev_score*0.5)
dataset=np.column_stack([hours_studied,attendance,prev_score,predicted_score])
print(dataset)
    

[[  1.   87.   85.   73.6]
 [  7.   59.   50.   77.7]
 [  6.   68.   84.   92.4]
 [  4.   73.   40.   61.9]
 [  4.   74.   83.   83.7]
 [  8.   52.   83.   97.1]
 [  1.   77.   82.   69.1]
 [  7.   57.   76.   90.1]
 [  2.   87.   65.   68.6]
 [  1.   84.   78.   69.2]
 [  5.   96.   55.   81.3]
 [  9.   87.   82.  112.1]
 [  7.   68.   70.   90.4]
 [  7.   98.   65.   96.9]
 [  7.   70.   67.   89.5]
 [  8.   66.   71.   95.3]
 [  5.   95.   42.   74.5]
 [  2.   68.   47.   53.9]
 [  8.   53.   53.   82.4]
 [  5.   73.   46.   69.9]
 [  5.   89.   64.   83.7]
 [  4.   59.   76.   75.7]
 [  2.   73.   75.   69.4]
 [  9.   56.   65.   94.3]
 [  8.   84.   87.  108.7]
 [  6.   73.   71.   87.4]
 [  4.   66.   44.   61.8]
 [  8.   61.   82.   99.3]
 [  5.   78.   71.   83.9]
 [  4.   83.   74.   81.9]
 [  5.   97.   71.   89.6]
 [  3.   71.   70.   71.3]
 [  1.   58.   44.   44.4]
 [  5.   91.   70.   87.3]
 [  8.   81.   83.  105.8]
 [  1.   85.   56.   58.5]
 [  8.   54.   73.   92.7]
 